### ISSUE TITLE
You don't need a `.no-sublime-package` file

### ISSUE THREAD

**Issue by FichteFoll** [MattDMo/PythonImproved#12]
In your changelog you listed that you added a `.no-sublime-package` file "to facilitate hacking".

However, this change actually does the opposite, see https://sublime.wbond.net/docs/customizing_packages and https://www.sublimetext.com/docs/3/packages.html. Each update would override all changes made, which wouldn't happen if the package was zipped.

So, please try to use `.no-sublime-package` only if your package just does not work when archived, for example when it depends on binaries. If you want to edit packages more easily, get https://sublime.wbond.net/packages/PackageResourceViewer or https://sublime.wbond.net/packages/Edit%20Preferences.

**Comment by FichteFoll** [comment]
The repo still contains ` .no-sublime-package`?

**Comment by MattDMo** [comment]
@FichteFoll right. It looks like the issue was for upgrading packages that formerly had a `.no-sublime-package` to a version that now supports the `.sublime-package` format. However, I'd still like to keep PI unpacked, so the guts are there for people to look at (and customize, if desired) and personally I like having it unpacked.

**Comment by FichteFoll** [comment]
I suggest you read on http://docs.sublimetext.info/en/latest/extensibility/packages.html (which was finished just yesterday).
