### ISSUE TITLE
Is the Django stuff necessary?

### ISSUE THREAD

**Issue by MattDMo** [MattDMo/PythonImproved#23]
I'm considering taking some (or maybe all) of the Django stuff out. `support.function.django.view.python` and `support.function.django.model.python` don't seem to be very useful, and some/many of the constants in `variable.other.django.settings.python` could conceivably be used in other contexts, where users would assume similar highlighting to all of their other all_caps constants. 

I kind of like `support.type.django.model.python` and `support.other.django.module.python`, but if anyone who cares to give feedback thinks they should be dumped as well, I'll take that into consideration.

**Comment by nickcoutsos** [comment]
I realize that django is hugely popular, but here's my vote to keep the syntax highlighting to standard Python. It's a shame that it's probably not easy for users to mixin additional highlighting rules as I can see that the django stuff would be very useful for many people. It isn't likely to ever really affect me anyway, though, as I don't randomly type django specific stuff.

On a related note, I'd like to raise the same question about the SQL related stuff. I'm doing a fair bit of automated tests for APIs which includes a number of strings like `"DELETE"` and `"POST"` to match the tested method. `"DELETE"` gets highlighted differently, presuming I've suddenly started writing an SQL query which is never the case. 

I can live with it, and I'm betting there are more people who find it convenient than those who find it annoying, but it just sort of rubs me the wrong way. It feels like the syntax highlighter is taking on responsibility of knowing what your code is doing instead of just what the code is saying.

Anyway, I hope my perspective helps. Thanks for your work on this project!

**Comment by MattDMo** [comment]
Django and SQL stuff removed in release [1.4.0](https://github.com/MattDMo/PythonImproved/releases/tag/1.4.0)
