### ISSUE TITLE
Python 3.5 is just around the corner

### ISSUE THREAD

**Issue by 1st1** [MattDMo/PythonImproved#45]
And a lot of people are playing with it already. Could you please release the new version, or at least provide some ETA?

**Comment by MattDMo** [comment]
Hi Yuri,
Hopefully soon, as in days, not months :grinning: I'm doing some final testing now, and discovered a few issues with one of the submitted PRs, which I'm trying to address. The Unicode support looks great, at least on my end, but it'll only be after real-world testing that I'm completely satisfied, so that's not going to hold anything up. 

I saw 3.5.0 is supposed to be released this coming Sunday, September 13, so hopefully PI 2.0 will be out by then. If you want to pull down the current version of the `unicode` branch and test on your own, I'd love to get your feedback.

**Comment by wldcordeiro** [comment]
This would be really great, the highlighting of `async`, `await` and the `@` operator would be nice.

**Comment by 1st1** [comment]
Matt, how about we release a 2.0.0 today and will release an update soon if something is broken? :)

**Comment by MattDMo** [comment]
See #46 - it ain't workin!

**Comment by vaultah** [comment]
Was there any reason to _close_ this issue?

**Comment by 1st1** [comment]
The only reason is that I personally wanted a 2.0 release with my async/await patch asap.  After waiting for quite some time, I decided to create my own highligher -- https://github.com/MagicStack/MagicPython, and no longer need PythonImproved.

**Comment by vaultah** [comment]
Yes, that's what I figured from the thread in Python-Ideas ML and MagicPython's README. Do you close issues you opened in other open source projects when you "no longer need" them?

**Comment by 1st1** [comment]
@vaultah This issue isn't about some bug or something that needs to be fixed or improved.  So what's the exact problem with me closing it?

**Comment by vaultah** [comment]
The reason *why* you closed it.

**Comment by MattDMo** [comment]
[*Cryptic Bacon*](https://github.com/MattDMo/PythonImproved/releases/tag/2.0.0) has been released! And it's only quarter to two in the morning! Ha ha!
