### ISSUE TITLE
Wrongly recognize instance creations as function calls.

### ISSUE THREAD

**Issue by asd123cqp** [MattDMo/PythonImproved#58]
![screen shot 2016-02-03 at 20 06 13](https://cloud.githubusercontent.com/assets/5053580/12802615/2451cf6a-cab2-11e5-8b86-daf4724e96a5.png)

As picture above:

in "test = Test(DISK)", the "Test" should be recognized as a class name, and it should be yellow.

 PythonImproved somehow thinks I am calling a function, which makes it green.

**Comment by MattDMo** [comment]
Hi, thanks for the feedback. There is no way for Python Improved to distinguish between a class instantiation, a method, or a function. In fact, when calling built-ins like `list()` or `bool()`, you are creating an instance of the `list` or `bool` class - they just happen to be spelled with all lowercase letters. Not all class names begin with capital letters, and not all functions/methods begin with lowercase, so unfortunately, within the framework Sublime uses for syntax highlighting, this just isn't possible without an IDE and code introspection.

**Comment by asd123cqp** [comment]
Thanks for your reply.

So is there any way you can make Python Improved to distinguish "functions that starts with capital" or "functions that follow by 'class ' "?

**Comment by MattDMo** [comment]
Names that come right after the `class` keyword are already highlighted selectively, as you show in your screen shot. Unfortunately, adding an additional scope for capitalized functions might be a little difficult. I'll see what I can do, but I can't promise anything at the moment.

**Comment by facelessuser** [comment]
I think scoping capitalized functions is going to down a bad road as it isn't even a Python syntax rule.  The requester is assuming that everyone using PythonImproved is editing code that is pep8 compliant.   There are a lot of Python libraries out their that are not.  There are libraries that use capitalized naming of normal functions.  Adding such functionality would make this more of a pep8 Python syntax highlighter.

I definitely wouldn't scope such functions as class, but you could give them a benign scoping of like "capitalized" or something, but I honestly think you would be wasting your time.  It would be something else entirely if the syntax highlighter actually had context information that could identify that you were calling an existing instance of a class, but since that info isn't available, I personally wouldn't waste time on trying to scope these class instantiations any different.  I'd hate to see themes jump on this and start coloring such scopings differently in a file that isn't using pep8 standards; it would just be confusing.

That's just my two cents.

**Comment by MattDMo** [comment]
@facelessuser Hey, want to drop me an email real quick? It's my username at my username dot com.

**Comment by asd123cqp** [comment]
Great points. Thank you guys.

**Comment by MattDMo** [comment]
After some thought, I agree with @facelessuser. Not everyone codes according to PEP-8 (unfortunately), and I can think of a number of modules/packages where this wouldn't work, not to mention thousands of examples on Stack Overflow where users have capitalized variables. It's just not worth the effort, and could very easily introduce bugs. Sorry.
