### ISSUE TITLE
Sublime Text 3

### ISSUE THREAD

**Issue by sheim** [MattDMo/PythonImproved#68]
Hi,

Are there any plans to have this available in ST3 as well?

Cheers,
Steve

**Comment by MattDMo** [comment]
Hi Steve,
This is available for ST3, and has been since the beginning. Just install via Package Control.

Matt

**Comment by sheim** [comment]
That's odd, while I find it via Package Control with ST2, I don't in ST3.
Is there some requirement to installation first?

**Comment by MattDMo** [comment]
Most likely you already have it installed. Check your settings to make sure it's not in the `ignored_packages` list. Otherwise, it should be listed in the syntax menu. I just checked https://packagecontrol.io/packages/Python%20Improved <https://packagecontrol.io/packages/Python%20Improved> and the "ST2/ST3" icon is still where it should be, right under the package's name and my name, so everything else is working - nothing has changed in months.

**Comment by sheim** [comment]
Yup solved, thanks and sorry for the bother.
