### ISSUE TITLE
Syntax highlighting error when `CREATE` keyword present

### ISSUE THREAD

**Issue by ochawkeye** [MattDMo/PythonImproved#7]
Sublime Text 2 Version 2.0.2, Build 2221 (Windows 7)
Python Improved v1.2.0

Python string syntax highlighting breaks when the word CREATE is used in combination with quotation marks.
```python
print "CREATE '%s'" % ('abc')  # Missing highlighting
print 'CREATE "%s"' % ('def')  # Missing highlighting
print "GRANT '%s'" % ('ghi')  # Highlighting ok
print "CREAT '%s'" % ('jkl')  # Highlighting ok
print "CREATE %s" % ('mno')  # Highlighting ok
print "create '%s'" % ('pqr')  # Highlighting ok
```
![sublime text python improved syntax highlighting](https://cloud.githubusercontent.com/assets/2996205/2573508/82af72f0-b921-11e3-9da1-11a5075e0801.png)

Expected behavior would be for %s to display in purple in all cases.
This issue exists with standard Python syntax language file in Sublime Text as well.

**Comment by MattDMo** [comment]
This is now fixed in release 1.4.2:

![pi_issue_7](https://cloud.githubusercontent.com/assets/1776358/6069193/7326259e-ad50-11e4-8007-6d51ef9e99e1.png)

I completely removed the SQL syntax highlighting, as it was distracting at best, and this seems to have addressed the issues with matching quotes and string substitutions.
